permalink: /:categories/:title/
markdown: kramdown
url: "http://codeforsanfrancisco.org"
baseurl: /sfbrigade-website
defaultbranch: gh-pages

owner:
  twitter: sfbrigade

prose:
  media: 'media'
  rooturl: '_posts'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
    - /js
  metadata:
    _posts/blog:
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "title"
        field:
          element: "text"
          label: "Title"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          options: "http://codeforsanfrancisco.org/api/tags.json?callback=tagsCallback"
          alterable: true
          placeholder: "Choose Tags"
      - name: "author"
        field:
          element: "select"
          label: "Author"
          options: "http://codeforsanfrancisco.org/api/authors.json?callback=authorsCallback"
    _posts/projects:
      - name: "layout"
        field:
          element: "hidden"
          value: "projects"
      - name: "category"
        field:
          element: "hidden"
          value: "projects"
      - name: "title"
        field:
          element: "text"
          label: "Title"
      - name: "lead"
        field:
          element: "text"
          label: "Short description"
          help: "This text shows up directly under the name of the project and should be a one sentence description."

exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
